use_frameworks!

target 'LLContainApp_Example' do
  pod 'LLContainApp', :path => '../'

  target 'LLContainApp_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
